"""add promo_text to language

Revision ID: 4c62f56f2ec4
Revises: a2423aa02107
Create Date: 2025-02-16 11:15:44.649650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c62f56f2ec4'
down_revision: Union[str, None] = 'a2423aa02107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('promo_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'promo_text')
    # ### end Alembic commands ###
