"""updated groups table

Revision ID: 7c0388797521
Revises: def8ee43ee28
Create Date: 2025-02-16 22:24:06.033973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0388797521'
down_revision: Union[str, None] = 'def8ee43ee28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('study_sessions', 'study_activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'study_activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('study_sessions', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
