"""remove_words_count_from_groups

Revision ID: def8ee43ee28
Revises: 156148f9932f
Create Date: 2025-02-16 21:07:11.282955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def8ee43ee28'
down_revision: Union[str, None] = '156148f9932f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'words_count')
    op.alter_column('study_sessions', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('study_sessions', 'study_activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'study_activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('study_sessions', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('groups', sa.Column('words_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
